### ISSUE TITLE
ZGPSwitch does not have battery property

### ISSUE THREAD

**Issue by chrisvis** [robmarkcole/Hue-sensors#1]
Hi Rob, 

I was trying you HASS component since I have a Hue tap and would like to attach some more automations to it. Nice work!

When starting HASS I got the following stack trace in the logs:
```
Traceback (most recent call last):
  File "/home/chip/havenv/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/chip/.homeassistant/custom_components/sensor/hue.py", line 28, in setup_platform
    data.update()
  File "/home/chip/havenv/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 306, in wrapper
    result = method(*args, **kwargs)
  File "/home/chip/.homeassistant/custom_components/sensor/hue.py", line 52, in update
    self.data = self.parse_hue_api_response(response.json())
  File "/home/chip/havenv/lib/python3.6/site-packages/hue_sensors.py", line 49, in parse_hue_api_response
    data_dict[_key] = parse_zpg(sensor)
  File "/home/chip/havenv/lib/python3.6/site-packages/hue_sensors.py", line 103, in parse_zpg
    'battery': response['config']['battery'],
KeyError: 'battery'
```

Looking at the Hue API response, the sensor looked like:
```json
 "6": {
    "state": {
      "buttonevent": 34,
      "lastupdated": "2017-10-12T17:16:42"
    },
    "swupdate": {
      "state": "notupdatable",
      "lastinstall": null
    },
    "config": {
      "on": true
    },
    "name": "Hue tap switch 1",
    "type": "ZGPSwitch",
    "modelid": "ZGPSWITCH",
    "manufacturername": "Philips",
    "uniqueid": "00:00:00:00:00:ab:cd:ef-ff"
  }
```

**Comment by robmarkcole** [comment]
Hi @chrisvis yes I see the problem, because these remotes actually don't have a battery but use a kinetic switch to generate charge :-) Will update.

http://www.ledinside.com/products/2015/8/philips_hue_tap_kinetic_smart_switch_powered_by_human_touch

**Comment by chrisvis** [comment]
Fixed!
